### ISSUE TITLE
Input layer name error running quantization

### ISSUE THREAD

**Issue by Mjonir** [majianjia/nnom#98]
Hello,

I am running into an error when running the quantization script on a model generated with tensorflow 2.3.1:

`quantisation list {'input_1': [0, 0], 'conv1d': [1, 0], 'conv1d_1': [0, 0], 'conv1d_2': [1, 0], 'max_pooling1d': [1, 0], 'conv1d_3': [2, 0], 'conv1d_4': [2, 0], 'conv1d_5': [3, 0], 'max_pooling1d_1': [3, 0], 'flatten': [3, 0], 'dropout': [3, 0], 'dense': [2, 0], 'dropout_1': [2, 0], 'dense_1': [1, 0], 'dense_2': [0, 0]}
quantizing weights for layer conv1d
    tensor_conv1d_kernel_0 dec bit 8
Traceback (most recent call last):
  File "main_keras.py", line 584, in <module>
    main()
  File "main_keras.py", line 581, in main
    port_to_uc()
  File "main_keras.py", line 575, in port_to_uc
    nnom.generate_model(classifier.model, classifier.validate_set.get_all_inputs(), name='weights.h')
  File "D:\Projects\FNH\deep_learning\nnom\scripts\nnom.py", line 746, in generate_model
    quantize_weights(model, per_channel_quant=per_channel_quant, name=name, format=format, layer_q_list=layer_q_list)
  File "D:\Projects\FNH\deep_learning\nnom\scripts\nnom.py", line 631, in quantize_weights
    layer_input_dec = layer_q_list[inp][0]
KeyError: 'input_1_1'`

It seems the input of the first actual layer (conv1d) is named "input_1_1", not "input_1" as in the quantisation list. Hacking the script to substitute the correct string allows it to keep running (until it hits a similar error on line 940).

**Comment by majianjia** [comment]
hi @Mjonir 

Please in python code, `del` your previous model before loading new model. The input_1_1 is caused by multi-instancing naming. 

https://github.com/majianjia/nnom/blob/ce83a10118a16bf77010b45114479ef1d609431d/examples/auto_test/main.py#L75

You can see in all example i must save/delete the model and clear the tf session before load it again and put it into quantisation. 

Hope it help,
Jianjia
